### ISSUE TITLE
Experience bar not moving in dungeons.

### ISSUE THREAD

**Issue by Rhindle7** [Sonaza/Experiencer#10]
74x Experiencer\modules\experience.lua:460: attempt to call global 'IsReferAFriendLinked' (a nil value)
Experiencer\modules\experience.lua:460: in function `HasRecruitingBonus'
Experiencer\modules\experience.lua:490: in function `CalculateXPMultiplier'
Experiencer\modules\experience.lua:548: in function `CalculateQuestLogXP'
Experiencer\modules\experience.lua:195: in function `GetText'
Experiencer\core.lua:574: in function `RefreshText'
Experiencer\core.lua:610: in function `Refresh'
Experiencer\core.lua:290: in function `RefreshModule'
Experiencer\core.lua:181: in function `Refresh'
Experiencer\modules\experience.lua:560: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Sonaza** [comment]
Apparently `IsReferAFriendLinked` was renamed to `IsRecruitAFriendLinked`.

I sooo reaally like all the pointless busywork Blizzard puts addon creators through, without having proper documentation either.

Should be fixed for v3.1.1.
