### ISSUE TITLE
show complete/incomplete quest XP with different colors on visualizer bar

### ISSUE THREAD

**Issue by killarny** [Sonaza/Experiencer#2]
It's handy to know whether I need to continue doing the quests I have incompleted, or if I can just go turn in what I have to level. 

The [Broker: XPBar](https://mods.curse.com/addons/wow/broker-xpbar) addon does this, but I like your addon better, so I'd love to switch over!

**Comment by Sonaza** [comment]
Added separate bar with different texture to distinguish them in update 2.0.6 going out now.
