### ISSUE TITLE
fix miscalculated XP percentage on text displays (broker and hover)

### ISSUE THREAD

**Issue by killarny** [Sonaza/Experiencer#3]
The text display for my XP percentage seems to be wrong - in the screenshot below I have the "show current and max XP" option selected, so it's showing that I have 258,700 current out of 506,000 max which is 51% - but the text says it's 48%. Below your addon in this screenshot, I am showing the text display from the [Broker: XPBar](https://mods.curse.com/addons/wow/broker-xpbar) addon which appears to have the percentage correct.

The rested XP amounts differ by 1% on each addon as well, but that could be attributed to a difference in rounding approaches.

![text](https://cloud.githubusercontent.com/assets/29001/17909598/65853e70-6942-11e6-8282-b317819f9270.png)

Interestingly, the bar texture seems to show the current XP at the right spot (shown here with Broker: XPBar above it this time, and the progress indicators match):

![bars](https://cloud.githubusercontent.com/assets/29001/17909602/6b188112-6942-11e6-81f0-1f469e4a615e.png)

**Comment by Sonaza** [comment]
Known bug, will be fixed when I have time.

**Comment by Sonaza** [comment]
Will be fixed in update 2.0.6 going out now.
