### ISSUE TITLE
frame stutters/pauses

### ISSUE THREAD

**Issue by aspryin** [Sonaza/Experiencer#6]
love the addon but after many reloads and pairing down of my other addons I have determined that this one addon is causing significant frame stuttering. I can stand in 1 spot spin in a circle with a keyboard turn and every 15 to 20 seconds the screen will pause then jump to the current view in game. I happens all the time. I look forward when this is fixed I’m not sure what is causing it. Good luck for a fix.

**Comment by Sonaza** [comment]
Did the frame stutter start after the last update to the addon? I fixed the AP calculator semi-blindly without personally testing completely it since I don't have an active subscription at the moment.

**Comment by aspryin** [comment]
I downloaded an older version 2.1.1 from Mar 31, 2017 and tested it flying above Dalaran with no stutter
I upgraded it to the current version no problems no stutter. I then replace the folder with the "stutter files" the old install. and it was back. something wackd a file in the origional addon files I had. so all is good

**Comment by Sonaza** [comment]
If that's solved it then good to hear.

In case the problem continues you can comment this issue again.
