### ISSUE TITLE
Map Refresh/Show

### ISSUE THREAD

**Issue by VacaTonta** [Sonaza/Experiencer#9]
## Expected Behavior
Bar stays hidden

## Actual Behavior
Reappears after opening map

## Steps to Reproduce the Problem

  1.Hide Bar (Use Titan Panel Broker)
  2.Open Map
  3.Bar rteappears

3.0.4 didnt fix the problem
using titan panel broker
moveanything can't hide it neither. once yes, but it will reappaear everytime i open the map

**Comment by Sonaza** [comment]
I am unable to reproduce the error.

Can you specify the reproduce steps some more? You're using maximized map? For me the bar does not reappear for me after hiding it and opening map.

**Comment by VacaTonta** [comment]
Hey! Thanks for the answer!
I am not using maximized map.
However, since the HIDE option didnt work for me before, I used MoveAnything to hide the frame called "ExperiencerFrame".
But with the latest patch. I can choose "hide bar" in the Experiencer Options from the Titan Panel Broker Plugin Options Tooltip and it does NOT matter wether I choose to hide that Frame with MoveAnything, reset the frame to its original values with MoveAnything and let it be shown, or choose "show Frame" in the Experiencer Options and play around with MoveAnything.
I do not know what produces the error. I only know that it only happens in the latest version...

**Comment by VacaTonta** [comment]
![wowscrnshot_090418_232312](https://user-images.githubusercontent.com/21964541/45058636-86a14180-b099-11e8-83fe-ffb9a2a6a2fc.jpg)

as you can see on the bottom is titan panel and about half of the lower titan panel is a little bit darker.
thats what it looks like after the latest update after i opened the map.
the experiecer option to hide the bar is on, so it should be hidden, however this "grey" panel with half opacaity is still there

**Comment by VacaTonta** [comment]
![wowscrnshot_090418_232532](https://user-images.githubusercontent.com/21964541/45058719-d54edb80-b099-11e8-980c-3ad992bf6e62.jpg)

this is what it should look like, now i hid the "ExperiencerFrame" with MoveAnything.
but as soon as i open the map it will look like pic 1 again

**Comment by VacaTonta** [comment]
i even reseted the frame in moveanything and cleared its cache so theat frame would NOT be affected by moveantyhing, but this grey half-opacity panel on the bottom will appear again and again after opening the map

**Comment by VacaTonta** [comment]
switched to titan panel heart of azeroth since  I couldn't find a fix :(
